#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$DIR"

echo "🔨 Building Manageur in release mode..."
swift build -c release

APP_NAME="Manageur"
TARGET_DIR="/Applications"
APP_BUNDLE="$TARGET_DIR/$APP_NAME.app"
CONTENTS_DIR="$APP_BUNDLE/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
RESOURCES_DIR="$CONTENTS_DIR/Resources"

echo "📦 Installing $APP_NAME to $APP_BUNDLE..."
rm -rf "$APP_BUNDLE"
mkdir -p "$MACOS_DIR"
mkdir -p "$RESOURCES_DIR"

BIN_PATH="$(swift build -c release --show-bin-path)/Manageur"
cp "$BIN_PATH" "$MACOS_DIR/$APP_NAME"
chmod +x "$MACOS_DIR/$APP_NAME"

# Copy Resource bundle if generated by SwiftPM
RESOURCE_BUNDLE="$(swift build -c release --show-bin-path)/Manageur_Manageur.bundle"
if [ -d "$RESOURCE_BUNDLE" ]; then
    ditto "$RESOURCE_BUNDLE" "$APP_BUNDLE/Manageur_Manageur.bundle"
fi

# Ensure App Icon is generated
if [ ! -f "$DIR/Sources/Manageur/Resources/AppIcon.icns" ]; then
    echo "🎨 Generating App Icon..."
    swift "$DIR/Scripts/generate_icon.swift"
fi

# Copy App Icon
if [ -f "$DIR/Sources/Manageur/Resources/AppIcon.icns" ]; then
    cp "$DIR/Sources/Manageur/Resources/AppIcon.icns" "$RESOURCES_DIR/AppIcon.icns"
fi
if [ -f "$DIR/Sources/Manageur/Resources/AppIcon.png" ]; then
    cp "$DIR/Sources/Manageur/Resources/AppIcon.png" "$RESOURCES_DIR/AppIcon.png"
fi

# Create Info.plist
cat <<EOF > "$CONTENTS_DIR/Info.plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.rasalp.manageur</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.productivity</string>
</dict>
</plist>
EOF

# Set the Finder icon via NSWorkspace
if [ -f "$RESOURCES_DIR/AppIcon.icns" ]; then
    echo "🎨 Setting Finder custom icon flag on $APP_BUNDLE..."
    swift -e "
import Cocoa
let appPath = \"$APP_BUNDLE\"
let icnsPath = appPath + \"/Contents/Resources/AppIcon.icns\"
if let img = NSImage(contentsOfFile: icnsPath) {
    let ok = NSWorkspace.shared.setIcon(img, forFile: appPath, options: [])
    print(ok ? \"   ✅ Finder icon set successfully\" : \"   ⚠️ NSWorkspace.setIcon failed\")
}
"
fi

# Touch and register with macOS LaunchServices
touch "$APP_BUNDLE"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP_BUNDLE" 2>/dev/null || true

echo "✅ Manageur is now installed in /Applications!"
echo "🚀 Launch it anytime from Launchpad, Spotlight, Finder, or with: open /Applications/Manageur.app"
